language: node_js
sudo: true
node_js: stable
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_448f66ee50ee_key -iv $encrypted_448f66ee50ee_iv -in .env.enc -out .env -d || true'
script:
- npm test
env:
  global:
  - CF_APP=natural-language-classifier-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/natural-language-classifier-nodejs
  skip_cleanup: true
notifications:
  email: false
